architecture:
  module: architectures.dreamer_v2
  name: DreamerV2
  action_key: action
  value_key: state_value

env:
  name: cheetah
  task: run
  seed: 0
  backend: dm_control
  frame_skip: 2
  from_pixels: True
  grayscale: False
  image_size : 64

collector:
  total_frames: 5_000_000
  init_random_frames: 1000
  frames_per_batch: 1000
  device: cpu

optimization:
  grad_clip: 100
  batch_size: 50
  batch_length: 50

  world_model_lr: 2e-4
  actor_lr: 4e-5
  value_lr: 1e-4
  slow_critic_update: 100
  kl_scale: 1.0 # 2.0 for continous control?
  optim_steps_per_batch: 100
  gamma: 0.99
  lambda: 0.95
  imagination_horizon: 15

networks:
  device: cuda:0
  state_vars: 32
  state_dim: 32
  rssm_hidden_dim: 300
  hidden_dim: 300
  mlp_dims: 300
  mlp_depth: 3
  activation: "elu"


replay_buffer: 
  uint8_casting: True
  buffer_size: 20000
  batch_size: 50
  scratch_dir: ${logger.exp_name}_${env.seed}

logger:
  backend: wandb
  project: dreamer-v1
  exp_name: ${env.name}-${env.task}-${env.seed}
  mode: online
  eval_iter: 10
  eval_rollout_steps: 100
