architecture:
  module: architectures.world_model
  name: WorldModel
  use_decoder_in_env: True  # for imagined pixels
  action_key: action
  value_key: state_value

env:
  name: CarRacing-v2
  task: ""
  seed: 0
  backend: gymnasium
  frame_skip: 2
  from_pixels: True
  grayscale: False
  image_size : 64

collector:
  total_frames: 500_000
  init_random_frames: 1000
  frames_per_batch: 1000
  #max_frames_per_traj: 1000
  device: cuda:0

optimization:
  #train_every: 1000
  grad_clip: 100
  batch_size: 50
  batch_length: 50

  world_model_lr: 6e-4
  #actor_lr: 8e-5
  #value_lr: 8e-5
  kl_scale: 1
  free_nats: 3.0
  optim_steps_per_batch: 100
  gamma: 0.99
  lambda: 0.95
  #imagination_horizon: 15

networks:
  exploration_noise: 0.3
  device: cuda:0
  state_dim: 30
  rssm_hidden_dim: 200
  hidden_dim: 200 #400
  activation: "elu"


replay_buffer: 
  uint8_casting: True
  buffer_size: 20000
  batch_size: 50
  scratch_dir: ${logger.exp_name}_${env.seed}

logger:
  backend: wandb
  project: dreamer-v1
  exp_name: ${env.name}-${env.task}-${env.seed}
  mode: online
  eval_iter: 10
  eval_rollout_steps: 100
